<?php
include '../../../connect.php';
require('../../../tcpdf/tcpdf.php');

date_default_timezone_set('Asia/Manila');

// Ensure the database connection is initialized
if (!$conn) {
    die("Database connection failed.");
}

// Retrieve parameters
$adjustment_id = isset($_GET['adjustment_id']) ? $_GET['adjustment_id'] : '';
$employee_id = isset($_GET['employee_id']) ? $_GET['employee_id'] : '';
$employee_name = isset($_GET['employee_name']) ? $_GET['employee_name'] : '';

if (empty($adjustment_id) || empty($employee_id) || empty($employee_name)) {
    die('Invalid parameters provided.');
}

// Extend TCPDF to customize watermark and footer
class PDFWithWatermark extends TCPDF {
    private $employee_id;
    private $employee_name;
    private $timestamp;

    // Constructor to receive employee details and timestamp
    public function __construct($employee_id, $employee_name) {
        parent::__construct();
        $this->employee_id = $employee_id;
        $this->employee_name = $employee_name;
        $this->timestamp = date('d M Y, h:i A');
    }

    // Watermark on each page
    public function addWatermark() {
        $this->SetFont('helvetica', 'B', 50);
        $this->SetTextColor(240, 240, 240); // Light gray for watermark

        $this->StartTransform();
        $this->Rotate(45, 105, 105);
        $this->Text(35, 190, $this->employee_id); // Display employee ID as watermark
        $this->StopTransform();
    }

    // Custom footer with employee details and timestamp
    public function Footer() {
        $this->SetY(-15);
        $this->SetFont('helvetica', 'I', 8);
        $footer_text = "Generated by: {$this->employee_name} | Employee ID: {$this->employee_id}  | Generated on: {$this->timestamp}";
        $this->Cell(0, 10, $footer_text, 0, 0, 'C');
    }

    // Include watermark on each page by calling it in the Header
    public function Header() {
        parent::Header();
        $this->addWatermark();
    }
}

try {
    // Prepare and execute SQL statement
    $stmtAdjustmentList = $conn->prepare('
        SELECT 
            material_request.material_request_id,
            material_request.timestamp,
            employee.first_name,
            employee.last_name,
            repair_request.repair_request_id,
            maintenance.maintenance_id,
            COALESCE(machine1.machine_name, machine2.machine_name) AS machine_name,  -- Use machine_name from second join if first is NULL
            material_request.status,
            item.image,
            item.item_name, 
            item.item_quantity,
            material_request_items.quantity
        FROM 
            material_request 
        LEFT JOIN 
            material_request_items ON material_request.material_request_id = material_request_items.material_request_id
        LEFT JOIN 
            item ON material_request_items.item_id = item.item_code
        LEFT JOIN
            employee ON material_request.requested_by = employee.employee_id
        LEFT JOIN
            repair_request ON material_request.repair_request_id = repair_request.repair_request_id
        LEFT JOIN 
            maintenance ON material_request.maintenance_id = maintenance.maintenance_id
        LEFT JOIN 
            machine_parts ON machine_parts.machine_part_item_code = item.item_code
        LEFT JOIN
            machine AS machine1 ON machine_parts.machine_id = machine1.machine_id  -- First LEFT JOIN to machine
        LEFT JOIN
            machine AS machine2 ON machine_parts.machine_id = machine2.machine_id  -- Second LEFT JOIN to machine
        WHERE 
            material_request.material_request_id = :material_request_id;
    ');

    $stmtAdjustmentList->bindParam(':material_request_id', $adjustment_id, PDO::PARAM_STR);
    if (!$stmtAdjustmentList->execute()) {
        throw new Exception("Failed to get adjustment details.");
    }

    $result = $stmtAdjustmentList->fetchAll(PDO::FETCH_ASSOC);
    if (empty($result)) {
        die('No adjustment details found.');
    }

    $firstRow = $result[0]; 

    // Initialize TCPDF with custom watermark and footer
    $pdf = new PDFWithWatermark($employee_id, $employee_name);
    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetTitle('Inventory Adjustment');
    $pdf->setHeaderFont(array('helvetica', '', 12));
    $pdf->setFooterFont(array('helvetica', '', 10));
    $pdf->SetMargins(15, 27, 15);
    $pdf->SetAutoPageBreak(TRUE, 25);
    $pdf->AddPage();

    // Title and Adjustment Code
    $pdf->SetFont('helvetica', 'B', 16);
    $pdf->Cell(0, 10, 'Material Request', 0, 1, 'C');
    $pdf->SetFont('helvetica', 'I', 10);
    $pdf->SetTextColor(100, 100, 100);
    $pdf->Cell(0, 10, 'Material Request Code: ' . $firstRow['material_request_id'], 0, 1, 'C');
    $pdf->Ln(10); // Line break

    // Reset color for details section
    $pdf->SetTextColor(0, 0, 0);

    // Date formatting
    $formattedDate = date('d M Y, h:i A', strtotime($firstRow['timestamp']));

    // Adjustment Details Section
    $pdf->SetFont('helvetica', '', 12);
    $pdf->Cell(50, 10, 'Requested Date:', 0, 0);
    $pdf->Cell(0, 10, $formattedDate, 0, 1);
    $pdf->Cell(50, 10, 'Requested By:', 0, 0);
    $pdf->Cell(0, 10, $firstRow['first_name'] . ' ' . $firstRow['last_name'], 0, 1);
    $pdf->Cell(50, 10, 'Repair / Maintenance No.:', 0, 0);
    $pdf->Cell(0, 10, $firstRow['repair_request_id'] ?? $firstRow['maintenance_id'], 0, 1);
    $pdf->Cell(50, 10, 'Status:', 0, 0);
    $pdf->Cell(0, 10, $firstRow['status'], 0, 1);
    $pdf->Ln(10);

    // Table Header
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->SetFillColor(52, 58, 64);
    $pdf->SetTextColor(255, 255, 255);

    // Header cells (Item Details and Quantity) with fixed widths
    $pdf->Cell(90, 10, 'Item Details', 1, 0, 'C', true);  // 90 width for 'Item Details'
    $pdf->Cell(45, 10, 'Requested Quantity', 1, 0, 'C', true);  // 45 width for 'Requested Quantity'
    $pdf->Cell(45, 10, 'Current Quantity', 1, 1, 'C', true);  // 45 width for 'Current Quantity'

    // Reset font and text color for the table content
    $pdf->SetFont('helvetica', '', 12);
    $pdf->SetTextColor(0, 0, 0);

    // Loop through each item in the result and add it to the PDF table
    foreach ($result as $row) {
        // Image and item name in one row
        $pdf->Cell(90, 20, '', 0, 0);  // Reserve space for image and item name
        
        // Set position to insert image (if available) and item name
        $pdf->SetXY($pdf->GetX() - 90, $pdf->GetY());

        // Check if an image exists for the item
        if (!empty($row['image'])) {
            // Display image if available
            $pdf->Image('@' . $row['image'], $pdf->GetX() + 2, $pdf->GetY() + 2, 15, 15);
        } else {
            // Display default image if no image is found
            $pdf->Image('@' . file_get_contents('../../../images/gallery.png'), $pdf->GetX() + 2, $pdf->GetY() + 2, 15, 15);
        }

        // Move the cursor to the right side of the image and add the item name
        $pdf->SetXY($pdf->GetX() + 20, $pdf->GetY());
        $pdf->Cell(70, 20, $row['item_name'], 0, 0, 'L');

        // Quantities in separate cells
        $pdf->Cell(45, 20, $row['quantity'], 0, 0, 'C');
        $pdf->Cell(45, 20, $row['item_quantity'], 0, 1, 'C');
    }

    // Output PDF to browser
    $pdf->Output('Material_Request_' . $adjustment_id . '.pdf', 'I');

} catch (Exception $e) {
    die('Error retrieving adjustment: ' . $e->getMessage());
}
?>
